[package]
name = "glox"
version = "0.1.5"
edition = "2024"
license = "MIT"
description = "A Reusable OpenGL renderer using GLOW"

[dependencies]
glow = ">=0.16.0"
glam = ">=0.27"
ply-rs = "0.1.3"

[dev-dependencies]
ggsdk = "0.1.10"